### ISSUE TITLE
Milestone 1.2: Publish first draft of mock shortened metadata for parallel development

### ISSUE THREAD

**Issue by richcsy** [Alzymologist/metadata-offline-project#2]
**Milestone 1:** Requirements specifications and latest metadata review
**Owner Org:** Alzymologist

**Comment by Slesarew** [comment]
closed by  example https://github.com/Alzymologist/substrate-parser/blob/95d7ea057c39539ca2459c300ef9f0d3901ad42f/examples/automated_short_meta.rs
